excluded:
  - .git**
  - Packages/Build/**
  - Build/**
  - "**/.build/**"
  - "**/.index-build/**"
  - "**/resource_bundle_accessor.swift"
  - Packages/**/.build/**
  - resource_bundle_accessor.swift
  - Pods
  - R.generated.swift
  - .build # Where Swift Package Manager checks out dependency sources

# 添加 Google Swift Style Guide 建議的規則
opt_in_rules:
  - anyobject_protocol
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - discouraged_direct_init
  - empty_string
  - explicit_init
  - explicit_top_level_acl
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - implicit_return
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - no_space_in_method_call
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_in_static_references
  - private_action
  - private_outlet
  - private_over_fileprivate
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_boolean
  - reduce_into
  - required_enum_case
  - shorthand_operator
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  #- vertical_whitespace_between_cases
  #- vertical_whitespace_closing_braces
  #- vertical_whitespace_opening_braces
  - void_return
